In [51]:
import pandas as pd
import numpy as np

df = pd.read_hdf('data/METR-LA.h5')
df

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
2012-03-01 00:00:00,64.375000,67.625000,67.125000,61.500000,66.875000,68.750000,65.125000,67.125000,59.625000,62.750000,...,45.625000,65.500000,64.500000,66.428571,66.875000,59.375000,69.000000,59.250000,69.000000,61.875000
2012-03-01 00:05:00,62.666667,68.555556,65.444444,62.444444,64.444444,68.111111,65.000000,65.000000,57.444444,63.333333,...,50.666667,69.875000,66.666667,58.555556,62.000000,61.111111,64.444444,55.888889,68.444444,62.875000
2012-03-01 00:10:00,64.000000,63.750000,60.000000,59.000000,66.500000,66.250000,64.500000,64.250000,63.875000,65.375000,...,44.125000,69.000000,56.500000,59.250000,68.125000,62.500000,65.625000,61.375000,69.857143,62.000000
2012-03-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2012-03-01 00:20:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-06-27 23:35:00,65.000000,65.888889,68.555556,61.666667,0.000000,54.555556,62.444444,63.333333,59.222222,65.333333,...,52.888889,69.000000,65.111111,55.666667,66.333333,62.444444,66.777778,64.888889,69.666667,62.333333
2012-06-27 23:40:00,61.375000,65.625000,66.500000,62.750000,0.000000,50.500000,62.000000,67.000000,65.250000,67.125000,...,54.000000,69.250000,60.125000,60.500000,67.250000,59.375000,66.000000,61.250000,69.000000,62.000000
2012-06-27 23:45:00,67.000000,59.666667,69.555556,61.000000,0.000000,44.777778,64.222222,63.777778,59.777778,57.666667,...,51.333333,67.888889,64.333333,57.000000,66.000000,62.666667,68.666667,63.333333,67.444444,61.222222
2012-06-27 23:50:00,66.750000,62.250000,66.000000,59.625000,0.000000,53.000000,64.285714,64.125000,60.875000,66.250000,...,51.125000,69.375000,61.625000,60.500000,65.625000,66.375000,69.500000,63.000000,67.875000,63.500000
2012-06-27 23:55:00,65.111111,66.888889,66.777778,61.222222,0.000000,49.555556,65.777778,65.111111,63.000000,61.666667,...,56.000000,67.444444,64.888889,60.888889,64.222222,66.444444,68.444444,63.555556,68.666667,61.777778

In [ ]:
#per censor data
c_mean = df.mean(numeric_only=True)
c_mean

773869    54.631359
767541    60.452789
767542    60.726120
717447    49.524287
717446    46.079798
            ...
717592    56.915083
717595    62.484679
772168    54.697381
718141    58.920210
769373    51.197504
Length: 207, dtype: float64

In [11]:
c_sd = df.std(numeric_only=True)
c_sd

773869    22.619199
767541    15.970239
767542    18.313353
717447    15.843261
717446    19.350345
            ...
717592    18.260438
717595    16.959238
772168    16.303651
718141    19.080474
769373    21.239354
Length: 207, dtype: float64

In [6]:
c_max = df.max()
c_max

773869    70.0
767541    70.0
767542    70.0
717447    70.0
717446    70.0
          ...
717592    70.0
717595    70.0
772168    70.0
718141    70.0
769373    70.0
Length: 207, dtype: float64

In [10]:
RCR = df/df.max()
RCR

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
2012-03-01 00:00:00,0.919643,0.966071,0.958929,0.878571,0.955357,0.982143,0.930357,0.958929,0.851786,0.896429,...,0.701923,0.935714,0.921429,0.948980,0.955357,0.848214,0.985714,0.846429,0.985714,0.883929
2012-03-01 00:05:00,0.895238,0.979365,0.934921,0.892063,0.920635,0.973016,0.928571,0.928571,0.820635,0.904762,...,0.779487,0.998214,0.952381,0.836508,0.885714,0.873016,0.920635,0.798413,0.977778,0.898214
2012-03-01 00:10:00,0.914286,0.910714,0.857143,0.842857,0.950000,0.946429,0.921429,0.917857,0.912500,0.933929,...,0.678846,0.985714,0.807143,0.846429,0.973214,0.892857,0.937500,0.876786,0.997959,0.885714
2012-03-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2012-03-01 00:20:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-06-27 23:35:00,0.928571,0.941270,0.979365,0.880952,0.000000,0.779365,0.892063,0.904762,0.846032,0.933333,...,0.813675,0.985714,0.930159,0.795238,0.947619,0.892063,0.953968,0.926984,0.995238,0.890476
2012-06-27 23:40:00,0.876786,0.937500,0.950000,0.896429,0.000000,0.721429,0.885714,0.957143,0.932143,0.958929,...,0.830769,0.989286,0.858929,0.864286,0.960714,0.848214,0.942857,0.875000,0.985714,0.885714
2012-06-27 23:45:00,0.957143,0.852381,0.993651,0.871429,0.000000,0.639683,0.917460,0.911111,0.853968,0.823810,...,0.789744,0.969841,0.919048,0.814286,0.942857,0.895238,0.980952,0.904762,0.963492,0.874603
2012-06-27 23:50:00,0.953571,0.889286,0.942857,0.851786,0.000000,0.757143,0.918367,0.916071,0.869643,0.946429,...,0.786538,0.991071,0.880357,0.864286,0.937500,0.948214,0.992857,0.900000,0.969643,0.907143
2012-06-27 23:55:00,0.930159,0.955556,0.953968,0.874603,0.000000,0.707937,0.939683,0.930159,0.900000,0.880952,...,0.861538,0.963492,0.926984,0.869841,0.917460,0.949206,0.977778,0.907937,0.980952,0.882540

In [52]:
df.index.dtype

dtype('<M8[ns]')

In [60]:
profile = pd.DataFrame(columns = df.columns)
for i in range(0,24):
    profile.loc[i] = df.loc[df.index.hour == i].mean()
profile

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
0,55.342988,59.647159,60.422327,55.579845,58.364798,51.698606,58.695528,58.409611,55.520053,58.878485,...,42.268903,61.331363,54.176634,55.602679,57.956997,55.455193,60.595713,57.905890,60.457305,55.695883
1,55.959190,60.433302,61.261297,56.576708,60.265567,52.370382,60.056355,59.320356,54.654873,57.986219,...,40.755594,62.289553,53.230385,54.865484,57.415498,55.717553,60.815428,58.373677,60.136459,56.622216
2,54.212028,59.599632,60.612881,54.943412,59.840652,51.655041,59.410943,58.738824,52.559064,56.185533,...,37.835392,60.509399,51.480859,53.464560,54.540550,54.540812,59.563434,57.209927,58.072381,55.243151
3,53.103349,58.404500,60.653429,53.011578,59.273959,51.298054,58.570870,58.116578,52.556119,56.671034,...,35.181914,59.100977,47.862272,52.981918,53.277532,52.954835,58.427136,57.266074,56.819765,55.293799
4,54.329286,57.135613,61.555687,53.370013,59.976454,52.954503,59.141209,56.828797,55.234957,59.737669,...,36.493478,59.716583,48.451550,54.857190,55.286017,53.969018,59.512717,59.258482,57.487496,57.524845
5,56.318081,57.502460,62.280332,53.411271,60.208929,55.270368,59.849557,57.375862,55.063155,58.573173,...,40.901857,61.251793,51.426644,57.462374,57.923453,54.718763,60.358623,59.548583,58.592270,58.940294
6,57.412179,58.317097,59.135308,50.574765,53.193527,53.357457,60.129476,57.710514,43.901239,34.707206,...,42.030053,61.383906,53.181197,59.437273,59.016713,56.004066,61.326656,51.444877,59.926249,53.736749
7,58.710718,59.705452,40.222411,48.135075,44.730325,49.658031,59.886284,57.619548,46.666392,25.452640,...,38.167795,62.130676,52.765427,60.960414,58.560973,57.729026,62.512124,46.166760,60.397552,53.469675
8,57.032187,59.725766,39.564912,48.360216,41.931593,50.366433,58.915715,57.770517,41.520086,25.373498,...,36.802484,62.073635,52.520449,60.761372,47.261577,57.567606,61.777321,44.314251,59.490884,45.487658
9,56.812308,59.483817,55.274807,46.444718,39.814248,48.765382,57.354881,57.789582,47.213388,26.683935,...,39.576648,61.148643,52.265605,60.146634,53.755502,56.021619,60.878919,45.909069,60.198802,48.981612
10,57.078562,59.653646,61.192033,45.978384,38.167506,48.934814,56.062157,56.490791,53.581824,33.362405,...,39.502594,60.567302,53.241627,59.727670,59.298198,55.670175,61.206260,48.648021,59.610262,48.301600
11,57.080267,61.526506,63.684693,48.813207,36.875092,53.204193,57.001118,56.330662,58.058465,44.176128,...,38.386886,62.532447,55.793956,60.913467,60.264885,56.197540,63.043991,53.086340,60.802368,48.564181
12,57.350058,61.530890,63.458830,48.647352,35.459280,53.777842,55.780829,54.540862,58.100015,50.266487,...,36.899995,62.007644,54.419221,60.970052,60.427437,56.172395,62.807863,53.502677,60.348230,48.956236
13,57.496543,61.255859,63.030776,46.890238,33.903260,52.274660,53.900089,53.408924,58.509521,52.381628,...,35.891578,61.576676,53.869101,60.693451,60.643266,56.291591,62.542554,53.154104,59.174309,50.392531
14,57.650786,61.598566,63.458441,46.817717,35.465817,52.571788,41.375109,53.076136,58.954281,56.700218,...,33.998009,61.889197,52.285252,61.482082,61.660167,56.901431,62.691531,51.836012,56.499414,50.799278
15,55.248560,62.100533,64.348677,45.244889,34.848302,50.637251,38.322616,52.848743,60.891383,62.462307,...,30.208918,54.587637,45.900193,63.223841,62.791986,58.283822,64.136418,51.759485,52.957679,48.599440
16,50.069274,61.941721,65.104019,41.001060,32.244352,45.524871,37.017078,53.277394,62.699364,64.907074,...,27.527643,37.241925,39.535840,64.321108,63.799766,59.482032,65.419213,52.783032,53.154341,39.264177
17,36.528920,59.562348,64.346590,38.065558,31.665813,42.878314,39.055399,53.901373,62.106150,64.264190,...,26.233523,31.605650,32.152812,63.937830,63.270022,58.807649,64.680980,51.399974,52.561255,34.606652
18,34.085379,59.474406,63.947209,42.159459,39.091981,45.740423,46.482980,56.585664,62.005536,62.492653,...,27.593263,36.702062,35.581565,62.983576,62.803067,58.729155,64.133217,53.586884,52.054973,40.642437
19,52.611963,62.691765,65.782762,48.743518,42.295513,49.948257,56.078118,60.274608,63.008729,63.789082,...,37.244946,57.732151,53.292201,63.364344,63.531105,59.914665,65.455664,59.806729,61.425245,49.151235
20,60.023532,63.362862,66.193383,54.195382,47.630128,53.785997,58.693585,61.826382,62.415080,64.388345,...,46.295037,65.837907,60.435344,62.904804,63.758741,59.926909,65.791699,62.230910,64.604418,56.706922
21,59.697331,62.077858,64.357166,53.461184,50.718355,52.391285,57.792443,60.477439,60.770865,63.230578,...,46.365506,64.849787,58.981941,60.967265,62.828421,58.520815,64.410756,61.197775,62.927439,57.871784
22,58.703123,61.874270,63.932109,52.631197,53.113400,51.019341,57.932614,60.615718,59.959660,63.210089,...,45.697505,63.858180,58.286591,60.037319,61.957554,58.201129,63.789322,61.246843,63.024937,57.063877
23,58.295994,62.260900,63.606800,55.526150,56.836290,52.764768,59.815450,60.787394,59.682861,63.043615,...,45.420689,63.835207,58.083884,59.031398,61.888716,58.184183,63.754751,61.100760,63.361008,56.823855